"""
Test that ServerProofManager can verify a proof
generated by ClientProofManager using PySNARK.
"""

import numpy as np

from secure_fl.proof_manager import ClientProofManager, ServerProofManager
from secure_fl.utils import compute_parameter_norm


def test_server_verifies_client_pysnark_proof():
    # --- 1. Create dummy "old" and "new" parameters -------------------------
    # Tiny model: one weight matrix (3x2) + bias (2,)
    old_params = [
        np.zeros((3, 2), dtype=np.float32),
        np.zeros((2,), dtype=np.float32),
    ]

    # Small update, within a reasonable norm bound
    updated_params = [
        np.ones((3, 2), dtype=np.float32) * 0.01,
        np.ones((2,), dtype=np.float32) * 0.01,
    ]

    # Delta from the client's perspective
    param_delta = [u - o for o, u in zip(old_params, updated_params)]
    delta_norm = compute_parameter_norm(param_delta, norm_type="l2")

    # --- 2. Client side: generate proof ------------------------------------
    client_pm = ClientProofManager(
        max_update_norm=10.0,  # allow fairly large updates
    )
    client_pm.use_pysnark = True  # ensure PySNARK path is active if available

    proof_inputs = {
        "client_id": "client_test_server",
        "round": 1,
        "data_commitment": "dummy_commitment",
        "initial_params": old_params,
        "updated_params": updated_params,
        "param_delta": param_delta,
        "learning_rate": 0.01,
        "local_epochs": 1,
        "rigor_level": "medium",
        "total_samples": 32,
    }

    proof_json = client_pm.generate_training_proof(proof_inputs)
    assert proof_json is not None

    # --- 3. Server side: verify proof --------------------------------------
    server_pm = ServerProofManager()
    # We don't need full snark setup for this test, because our
    # verify_client_proof uses hashes + norms and treats SNARK as mock.
    server_pm.setup_complete = True

    ok = server_pm.verify_client_proof(
        proof_json,
        updated_parameters=updated_params,  # as NDArrays
        old_global_params=old_params,
    )

    assert ok, "Server should accept a valid client proof"

    print("Server verification of client PySNARK-backed proof: OK")


if __name__ == "__main__":
    test_server_verifies_client_pysnark_proof()
